php_packages:
  - { name: dev, package: php5-dev }
  - { name: pear, package: php-pear }
  - { name: xdebug, package: php5-xdebug }
  - { name: curl, package: php5-curl }
  - { name: mcrypt, package: php5-mcrypt }
  - { name: mysql, package: php5-mysql }
  - { name: redis, package: php5-redis }
  - { name: apc, package: php-apc }

php_extensions:
  - { name: "jsmin", package: "pecl.php.net/jsmin-beta" }
  - { name: "mongo", package: "pecl.php.net/mongo" }
  - { name: "xhprof", package: "pecl.php.net/xhprof-beta" }
